sources:
  bundler: true
allowed:
  - 0bsd
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - mit
  - ruby

ignored:
  bundler:
    - rchardet # Ruby terms
    - strscan # Ruby

reviewed:
  bundler:
    - activerecord # MIT
    - coderay # MIT
    - concurrent-ruby # MIT
    - css_parser # MIT
    - excon # MIT
    - faraday-em_http # MIT
    - faraday-em_synchrony # MIT
    - faraday-excon # MIT
    - faraday-httpclient # MIT
    - faraday-patron # MIT
    - faraday-net_http # MIT
    - faraday-rack # MIT
    - highline # GPL-2.0 OR Ruby terms
    - htmlentities # MIT
    - image_size # MIT
    - io-wait # Ruby terms
    - json # Ruby terms
    - jwt # MIT
    - kgio # LGPL-2.1+
    - logstash-event # Apache-2.0
    - net-http # Ruby
    - net-imap # Ruby
    - net-pop # Ruby
    - net-protocol # Ruby
    - net-smtp # Ruby
    - omniauth # MIT
    - openssl # Ruby terms
    - pg # Ruby terms
    - r2 # Apache-2.0 (Twitter)
    - racc # Ruby terms
    - raindrops # LGPL-2.1+
    - rubyzip # Ruby terms
    - sidekiq # LGPL (Sidekiq)
    - tilt
    - timeout # Ruby
    - unf # BSD-2-Clause
    - unicorn
    - uri # Ruby
