name: Linting

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: linting-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Setup gems
        run: |
          gem install bundler --conservative -v $(awk '/BUNDLED WITH/ { getline; gsub(/ /,""); print $0 }' Gemfile.lock)
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn install

      - name: Rubocop
        if: ${{ always() }}
        run: bundle exec rubocop .

      - name: ESLint (core)
        if: ${{ always() }}
        run: yarn eslint app/assets/javascripts

      - name: ESLint (core plugins)
        if: ${{ always() }}
        run: yarn eslint plugins

      - name: Prettier
        if: ${{ always() }}
        run: |
          yarn prettier -v
          yarn prettier --list-different \
            "app/assets/stylesheets/**/*.scss" \
            "app/assets/javascripts/**/*.js" \
            "plugins/**/assets/stylesheets/**/*.scss" \
            "plugins/**/assets/javascripts/**/*.js"

      - name: Ember template lint
        if: ${{ always() }}
        run: |
          yarn ember-template-lint \
            app/assets/javascripts \
            plugins/**/assets/javascripts

      - name: English locale lint (core)
        if: ${{ always() }}
        run: bundle exec ruby script/i18n_lint.rb "config/**/locales/{client,server}.en.yml"

      - name: English locale lint (core plugins)
        if: ${{ always() }}
        run: bundle exec ruby script/i18n_lint.rb "plugins/**/locales/{client,server}.en.yml"
